# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 019de1902cee77560d2bab0b3da97b9b5a9bc376c63d248ddcf49382ca91cafa36b81e5822c5b410344130b4b0ae55386bbb74ae8654cc7136c8d4444dc5231a

test:
  secret_key_base: c1a206829e55883f49d08241bc2088f1a709fa9db040095f4a0d3f10587927c3d59820bb8a1c610be3ea6c28589b5bc4e3d400d13f011d98eae88396d46e248b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
